### 1. 字典的初始化

In [1]:
a = dict([('a',4),('b',3),('3','b')])
print(a)

b = dict(zip('abc', [5, 1, 3]))
print(b)

c = {'a':1, 1:2, 3:'b'}
print(c)

# d = dict(a = 1,d='f', c = 2)
# print(d)

t1 = [1,2,3]
t2 = ['a','b','c']
dictionary = dict(zip(t2,t1))
print(dictionary)
print(list(zip(t2,t1)))

{'a': 4, 'b': 3, '3': 'b'}
{'a': 5, 'b': 1, 'c': 3}
{'a': 1, 1: 2, 3: 'b'}
{'a': 1, 'b': 2, 'c': 3}
[('a', 1), ('b', 2), ('c', 3)]


In [2]:
a = {'a':1, 1:2, 3:'b'}
print(a)
b  = dict([('a', 'b'),(1,2),(3,'c')])
print(b)
c = dict(a = 1, b = 3)
print(c)
d = dict(zip('abc', [1,2,3]))
print(d)
e = dict(zip(['a', 1, 'b'], [2, 'c', 3]))
print(e)

l = dict((k, v) for k,v in enumerate(['a','b','c','d']))
print(l)
print(dict((v,k) for k,v in l.items()).items())
l = {4:'d',3:'c',2:'b',1:'a'}
print(type(l.items()))
print(dict((k,v) for k,v in l.items()))

{'a': 1, 1: 2, 3: 'b'}
{'a': 'b', 1: 2, 3: 'c'}
{'a': 1, 'b': 3}
{'a': 1, 'b': 2, 'c': 3}
{'a': 2, 1: 'c', 'b': 3}
{0: 'a', 1: 'b', 2: 'c', 3: 'd'}
dict_items([('a', 0), ('b', 1), ('c', 2), ('d', 3)])
<class 'dict_items'>
{4: 'd', 3: 'c', 2: 'b', 1: 'a'}


### 2.pandas读入字典数据

In [3]:
import pandas as pd
voc = {1:'a', 2:'b', 3:'c', 4:'d'}
print(voc)
voc_reverse = dict((v,k) for k,v in voc.items())  #为什么网页上的是按顺序的
# print(help(pd.DataFrame.from_dict))
word = pd.DataFrame(voc_reverse, index=['voc'])
word.index = ['number']
print(word)

word2 = pd.DataFrame.from_dict(voc_reverse, orient='index')
word2.columns = ['id']
print(word2)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}
        a  b  c  d
number  1  2  3  4
   id
a   1
b   2
c   3
d   4


### 3. 生成器的使用 ---生成值的序列

参考[解释 yield 和 Generators（生成器）](http://python.jobbole.com/87613/)

#### 3.1 简单的生成器理解

In [4]:
a = (s for s in range(7))  # 这里生成的是一个生成器
b = [s for s in range(7)]
print(a)
print(sum(a))          #迭代器已经使用过数据
print(list(a), '\n')   #所以这里输出一个空的列表
print(b)
print(sum(b))
print(list(b))

<generator object <genexpr> at 0x0000014D831531A8>
21
[] 

[0, 1, 2, 3, 4, 5, 6]
21
[0, 1, 2, 3, 4, 5, 6]


In [44]:
# while循环是用来确保生成器函数永远也不会执行到函数末尾，虽然每次迭代器到结束后，可以再次创建新的迭代器，但是该方法太愚蠢了
def gen_number():
    while True:    
        for i in range(10):
            yield i
gen = gen_number() # 该语句产生一个生成器

In [45]:
next(gen)

0

#### 3.2 生成器例子

In [46]:
# 找出输入列表中的素数
import math
def is_prime(number):      
    # 判断是否是质数，素数；定义：指在大於1的自然数中，除了1和該数自身外，無法被其他自然数整除的数
    if number > 1:
        if number == 2:      # 2是最小的质数
            return True
        if number % 2 == 0:  # 偶数都是合数
            return False
        for current in range(3, int(math.sqrt(number) + 1), 2):  # 在奇数中寻找质数
            # print(current)
            if number % current == 0: 
                return False
        return True
    return False
def get_primes1(input_list):
    # 找到质数并放到新的列表中
    result_list = list()
    for element in input_list:
        if is_prime(element):
            result_list.append(element)
 
    return result_list
 
def get_primes2(input_list):
    return [element for element in input_list if is_prime(element)]

def get_primes3(number):  # 通过生成器可以处理无穷的序列
    while True:
        if is_prime(number):
            yield number    
        number += 1      # 逐渐累加直到找到下一个素数然后返回
        print(number)
gen = get_primes3(11)    # 生成器只需进行一次初始化，然后使用next()就可以逐渐迭代了

In [57]:
print(gen)  # 迭代器的起始地址，不会变
next(gen)

<generator object get_primes3 at 0x00000231612E4CA8>
44
45
46
47


47

In [43]:
# 找到比一个数的等比级数大的最小素数
def get_primes(number):
    while True:
        if is_prime(number):
            print('------------',number,'-----------')
            number = yield number
            print('****************', number)
        number += 1
def print_successive_primes(iterations, base=10):
    prime_generator = get_primes(base)
    prime_generator.send(None)
    for power in range(iterations):
        print('the {}-th output'.format(str(power)))
        print(prime_generator.send(base ** power)) # 把参数值传到yield赋值地方，number = yield number将参数赋给第一个number
gen = print_successive_primes(3)

------------ 11 -----------
the 0-th output
**************** 1
------------ 2 -----------
2
the 1-th output
**************** 10
------------ 11 -----------
11
the 2-th output
**************** 100
------------ 101 -----------
101


In [10]:
import random
 
def get_data():
    """返回0到9之间的3个随机数"""
    return random.sample(range(10), 3)
 
def consume():
    """显示每次传入的整数列表的动态平均值"""
    running_sum = 0
    data_items_seen = 0
 
    while True:
        data = yield
        data_items_seen += len(data)
        running_sum += sum(data)
        print('The running average is {}'.format(running_sum / float(data_items_seen)))
        print(running_sum, data_items_seen)
 
def produce(consumer):
    """产生序列集合，传递给消费函数（consumer）"""
    while True:
        data = get_data()
        print('Produced {}'.format(data))
        consumer.send(data)
        yield             # 循环一次先保存状态并暂时退出，否则会出现死循环，yield本身不会返回值
 
if __name__ == '__main__':
    consumer = consume()
    consumer.send(None)   # 当用send启动生成器，第一次执行到yield时要发送空的值
    producer = produce(consumer)
 
    for _ in range(10):
        print('Producing...')
        next(producer)

Producing...
Produced [6, 0, 1]
The running average is 2.3333333333333335
7 3
Producing...
Produced [1, 8, 2]
The running average is 3.0
18 6
Producing...
Produced [5, 0, 2]
The running average is 2.7777777777777777
25 9
Producing...
Produced [7, 3, 0]
The running average is 2.9166666666666665
35 12
Producing...
Produced [4, 0, 7]
The running average is 3.066666666666667
46 15
Producing...
Produced [0, 3, 7]
The running average is 3.111111111111111
56 18
Producing...
Produced [2, 3, 4]
The running average is 3.0952380952380953
65 21
Producing...
Produced [5, 6, 9]
The running average is 3.5416666666666665
85 24
Producing...
Produced [6, 7, 9]
The running average is 3.962962962962963
107 27
Producing...
Produced [3, 8, 6]
The running average is 4.133333333333334
124 30


In [2]:
a= max([1,2,3,1,4,2])
a

4

In [2]:
import pandas as pd
a = pd.Series([1,2,3,3,2,6])
a

0    1
1    2
2    3
3    3
4    2
5    6
dtype: int64

In [17]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape([3,3])
print(b)
print(type(b))
print(b.shape, '\n')
c = a.reshape([1,3,-1])
print(c)
print(type(c))
print(c.shape)
print()

print('c[0]=', c[0])
print('c[0][1]=', c[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(1, 3, 3)

c[0]= [[1 2 3]
 [4 5 6]
 [7 8 9]]
c[0][1]= [7 8 9]


In [18]:
a = np.array([1,2,3])
print(a.reshape([3,1]))

[[1]
 [2]
 [3]]
